FROM ubuntu:latest
RUN apt-get install -y iproute2 net-tools
RUN apt-get update && apt-get install -y isc-dhcp-server
COPY dhcpd.conf /etc/dhcp/dhcpd.conf
EXPOSE 67/udp
CMD ["dhcpd", "-f", "-d", "--no-pid"]