FROM ubuntu:latest
RUN apt-get update && apt-get install -y isc-dhcp-server
RUN apt-get install -y iproute2 net-tools
RUN mkdir -p /var/lib/dhcp/ && chmod -R 777 /var/lib/dhcp/
RUN touch /var/lib/dhcp/dhcpd.leases
COPY dhcpd.conf /etc/dhcp/dhcpd.conf
EXPOSE 67/udp
CMD ["dhcpd", "-f", "-d", "--no-pid"]